spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:asset_market}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

assetmarket:
  app:
    jwtSecret: "======================YourSecretKeyHere======================"
    jwtExpirationMs: 86400000

logging:
  level:
    com.assetmarket.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:REDACTED_BOT_TOKEN}
